### ISSUE TITLE
"Streamline" ability to return to WiiU home screen from within usb loader GX

### ISSUE THREAD

**Issue by Nomelas** [GreyWolfSC/streamline#3]
It's certainly possible.... since it would just require hooking into the Wii channel HCVA (Wii U Menu) similar to how Wiiflow lite does it.

Suggestion: add it to/replace the Wii menu option in the loader's home menu. or have a toggle in the options to switch between Wii, and Wii U menu.

**Comment by GreyWolfSC** [comment]
Thanks for the suggestion but I have no plans to implement this. I do not have a Wii U to test it and this loader is intended for original Wiis and vWii mode only.

**Comment by Nomelas** [comment]
it would just be a mater of having it launch this title/channel: HCVA
http://www.gametdb.com/Wii/HCVA

maybe a flag you could add in GXGlobal.cfg ?

one idea is a "launch title on exit" or something, similar to "return to"
